### ISSUE TITLE
Output Image is completely gray One

### ISSUE THREAD

**Issue by r-anupama** [shivaniarbat/Image-Segmentation-UNet-MALIS#1]
The 0_predict image is fully gray image no Segments found
how you fix this?

**Comment by skh0619** [comment]
Me too, The 0_predict image is fully gray image no Segments found
how you fix this?

**Comment by shivaniarbat** [comment]
I experimented with the existing model to train this log data. However I did not work on this issue for U-Net model instead I designed a new approach to work on this problem. You can read and learn all about this approach ----> https://github.com/shivaniarbat/Image-Segmentation-Scanned-Log-Data
